/* ═══════════ BUSINESS ═══════════ */

SUBJECTS.push({
  id: 'business',
  name: 'Business',
  short: 'Business',
  accent: 'teal',
  level: 'MBA core plus practitioner depth, Indian context included',
  blurb: 'Business is a set of loosely coupled disciplines held together by one question: where does durable profit come from, and what destroys it. Frameworks are cheap; knowing which one a situation calls for, and where it stops being true, is the skill.',
  sections: [
    { title: 'Strategy', note: '', topics: [
      ['Industry analysis', 'Porter\'s five forces, industry structure, profit pool mapping'],
      ['Competitive advantage', 'cost leadership vs differentiation, the stuck-in-the-middle critique'],
      ['Resource-based view', 'VRIO framework, core competences, dynamic capabilities'],
      ['Value chain analysis', 'primary and support activities, where margin actually sits'],
      ['Corporate strategy', 'diversification, vertical integration, portfolio matrices, conglomerate discount'],
      ['Growth strategy', 'Ansoff matrix, adjacency expansion, build vs buy vs partner'],
      ['Disruption theory', 'sustaining vs disruptive innovation, jobs to be done, and the critiques'],
      ['Platform and network strategy', 'network effects, multi-homing, chicken-and-egg, winner-take-most'],
      ['Blue ocean and value innovation', 'creating uncontested space; strategy canvas'],
      ['Strategy execution', 'OKRs, balanced scorecard, strategy-to-operations translation'],
    ]},
    { title: 'Marketing', note: '', topics: [
      ['Segmentation, targeting, positioning', 'the STP sequence and how positioning is actually chosen'],
      ['Marketing mix', 'product, price, place, promotion; the 7Ps for services'],
      ['Consumer behaviour', 'decision process, involvement, reference groups, behavioural influences'],
      ['Brand management', 'brand equity models, architecture, extensions, repositioning'],
      ['Pricing strategy', 'cost-plus, value-based, penetration vs skimming, price discrimination'],
      ['Distribution channels', 'channel design, conflict, disintermediation, omnichannel'],
      ['Digital marketing', 'SEO, performance marketing, attribution, CAC and LTV'],
      ['Marketing research', 'qualitative and quantitative methods, conjoint analysis, A/B testing'],
      ['Customer analytics', 'cohort analysis, churn, RFM segmentation, net promoter score'],
      ['B2B and services marketing', 'buying centres, relationship selling, service quality gaps'],
    ]},
    { title: 'Accounting and financial statements', note: '', topics: [
      ['Accounting equation and double entry', 'assets, liabilities, equity; debits and credits'],
      ['Financial statements', 'balance sheet, profit and loss, cash flow statement and how they link'],
      ['Accrual vs cash accounting', 'revenue recognition, matching principle, deferrals'],
      ['Inventory and depreciation', 'FIFO, weighted average, straight line vs written down value'],
      ['Ratio analysis', 'liquidity, solvency, profitability, efficiency, DuPont decomposition'],
      ['Cash flow analysis', 'operating, investing, financing; free cash flow'],
      ['Accounting standards', 'Ind AS and IFRS convergence, key differences from US GAAP'],
      ['Consolidation', 'subsidiaries, associates, goodwill, minority interest'],
      ['Cost and management accounting', 'absorption vs marginal costing, activity-based costing, variance analysis'],
      ['Earnings quality and red flags', 'aggressive recognition, related party dealings, Beneish-style signals'],
    ]},
    { title: 'Corporate finance', note: '', topics: [
      ['Time value of money', 'discounting, annuities, perpetuities, effective rates'],
      ['Capital budgeting', 'NPV, IRR and its pitfalls, payback, profitability index'],
      ['Cost of capital', 'CAPM, beta, WACC, hurdle rate setting'],
      ['Capital structure', 'Modigliani–Miller, trade-off theory, pecking order, optimal leverage'],
      ['Working capital management', 'cash conversion cycle, receivables, inventory, payables'],
      ['Valuation', 'DCF, comparable companies, precedent transactions, sum of the parts'],
      ['Dividend and payout policy', 'dividends vs buybacks, signalling, Indian dividend taxation'],
      ['Mergers and acquisitions', 'synergy estimation, due diligence, accretion-dilution, integration'],
      ['Private equity and venture capital', 'term sheets, cap tables, dilution, exit routes'],
      ['Risk management and hedging', 'currency, interest rate and commodity exposure'],
    ]},
    { title: 'Operations and supply chain', note: '', topics: [
      ['Process analysis', 'throughput, bottlenecks, Little\'s law, capacity utilisation'],
      ['Quality management', 'statistical process control, six sigma, total quality management'],
      ['Lean operations', 'Toyota production system, muda, kanban, just in time'],
      ['Inventory management', 'EOQ, safety stock, reorder point, newsvendor model'],
      ['Supply chain design', 'sourcing, network configuration, bullwhip effect, resilience'],
      ['Logistics and distribution', 'transportation modes, warehousing, last mile, cold chain'],
      ['Project management', 'critical path, PERT, agile methods, earned value'],
      ['Service operations', 'queueing, capacity vs demand, yield management'],
      ['Procurement and vendor management', 'negotiation, contracts, supplier scorecards'],
      ['Sustainability in operations', 'circular economy, emissions accounting, ESG in supply chains'],
    ]},
    { title: 'Organisation and people', note: '', topics: [
      ['Organisational structure', 'functional, divisional, matrix, network; span of control'],
      ['Motivation theories', 'Maslow, Herzberg, expectancy, self-determination; intrinsic vs extrinsic'],
      ['Leadership', 'trait, behavioural, situational and transformational models'],
      ['Teams and group dynamics', 'formation stages, groupthink, psychological safety'],
      ['Organisational culture', 'Schein\'s levels, artefacts vs assumptions, culture change'],
      ['Change management', 'Kotter\'s steps, Lewin\'s model, resistance and its sources'],
      ['Talent management', 'recruitment, onboarding, performance appraisal, succession planning'],
      ['Compensation and incentives', 'pay structures, variable pay, ESOPs, incentive distortion'],
      ['Negotiation', 'BATNA, ZOPA, integrative vs distributive bargaining'],
      ['Decision making and bias', 'anchoring, sunk cost, escalation of commitment, overconfidence'],
    ]},
    { title: 'Entrepreneurship and new ventures', note: '', topics: [
      ['Opportunity identification', 'problem-solution fit, market sizing, TAM SAM SOM'],
      ['Business model design', 'business model canvas, unit economics, revenue models'],
      ['Lean startup method', 'MVP, build-measure-learn, pivot criteria and its critics'],
      ['Product-market fit', 'measuring it honestly, retention curves, leading indicators'],
      ['Fundraising', 'stages from angel to growth, valuation, dilution, SAFEs and convertibles'],
      ['Founder and team dynamics', 'equity splits, vesting, co-founder conflict'],
      ['Go-to-market', 'sales motion selection, pricing experiments, channel-led growth'],
      ['Scaling', 'hiring ahead of need, process debt, when structure must change'],
      ['Failure modes', 'premature scaling, cash mismanagement, founder-market mismatch'],
      ['Indian startup ecosystem', 'DPIIT recognition, funding winters, unicorn cohorts, regulatory hurdles'],
    ]},
    { title: 'Business economics and analytics', note: '', topics: [
      ['Demand and elasticity', 'price, income and cross elasticity; revenue implications'],
      ['Cost structures', 'fixed vs variable, economies of scale and scope, learning curves'],
      ['Market structures for managers', 'competition, oligopoly pricing, monopolistic competition'],
      ['Game theory in business', 'entry deterrence, price wars, commitment, signalling'],
      ['Macro environment', 'interest rates, inflation, exchange rates and their effect on the firm'],
      ['Forecasting', 'time series methods, regression, judgemental forecasting, error metrics'],
      ['Statistical inference for business', 'sampling, confidence intervals, significance in practice'],
      ['Experimentation', 'A/B tests, sample size, novelty effects, causal inference in business data'],
      ['Data visualisation and reporting', 'dashboards, chart selection, metric hierarchies'],
      ['Business intelligence stack', 'warehouses, ETL, self-service analytics, data governance'],
    ]},
    { title: 'Governance, ethics and business law', note: '', topics: [
      ['Corporate governance', 'board structure, independent directors, shareholder rights'],
      ['Agency problems', 'principal-agent conflict, promoter-dominated firms, related party transactions'],
      ['Business ethics frameworks', 'consequentialist, deontological and virtue approaches applied to firms'],
      ['Stakeholder theory', 'shareholder primacy vs stakeholder capitalism'],
      ['ESG and sustainability reporting', 'BRSR in India, greenwashing risk, materiality'],
      ['Compliance and risk', 'internal controls, whistleblowing, anti-bribery, audit committees'],
      ['Contract essentials for managers', 'formation, key clauses, indemnity, termination'],
      ['Competition and consumer law', 'anti-competitive conduct, dominance, consumer protection duties'],
      ['Employment law basics', 'contracts, termination, POSH compliance, labour codes'],
      ['Corporate failures as case studies', 'what governance missed at Satyam, Enron, IL&FS'],
    ]},
    { title: 'International and digital business', note: '', topics: [
      ['Market entry modes', 'export, licensing, joint venture, wholly owned subsidiary'],
      ['Cross-border strategy', 'global vs multidomestic vs transnational; CAGE distance framework'],
      ['Global supply chains', 'offshoring, nearshoring, China plus one, tariff exposure'],
      ['Foreign exchange for firms', 'transaction, translation and economic exposure'],
      ['Cross-cultural management', 'Hofstede and GLOBE dimensions, expatriate management'],
      ['Digital transformation', 'legacy modernisation, process digitisation, change resistance'],
      ['Technology strategy', 'build vs buy, platform choices, technical debt as a business cost'],
      ['AI adoption in business', 'use case selection, workflow redesign, measurement, governance'],
      ['Cybersecurity and data as business risk', 'breach cost, privacy regulation, DPDP Act obligations'],
      ['Indian regulatory landscape for business', 'GST, FDI policy, PLI schemes, ease of doing business realities'],
    ]},
  ]
});
