/* ═══════════ FINANCE ═══════════ */

SUBJECTS.push({
  id: "finance",
  name: "Finance",
  short: "Finance",
  accent: "indigo",
  level: "Graduate / PhD qualifying-exam depth",
  blurb: "Asset pricing and corporate finance are the two theoretical pillars; stochastic calculus and empirical method are the tools that make them operational. Practice areas sit on top and change faster than the theory.",
  sections: [
    { title: "Mathematical foundations", note: "", topics: [
      ["Measure-theoretic probability", "probability spaces, filtrations, conditional expectation"],
      ["Stochastic processes", "Markov processes, martingales, stopping times"],
      ["Brownian motion & It\u00f4 calculus", "It\u00f4's lemma, stochastic integrals, SDEs"],
      ["Change of measure", "Girsanov, Radon\u2013Nikodym derivative, risk-neutral measure"],
      ["Jump processes", "Poisson and L\u00e9vy processes, jump-diffusion"],
      ["PDE methods", "Feynman\u2013Kac, Black\u2013Scholes PDE, boundary conditions"],
      ["Numerical methods", "binomial trees, finite differences, Monte Carlo, variance reduction"],
      ["Optimisation & dynamic programming", "portfolio problems in continuous and discrete time"],
    ]},
    { title: "Asset pricing theory", note: "", topics: [
      ["No arbitrage & law of one price", "the organising principle of the field"],
      ["Fundamental theorems of asset pricing", "equivalence of no arbitrage and a pricing measure"],
      ["Stochastic discount factor", "the single equation everything else specialises"],
      ["Complete vs incomplete markets", "spanning, replication, market frictions"],
      ["Mean-variance analysis", "efficient frontier, two-fund separation"],
      ["CAPM", "derivation, testable implications, Roll's critique"],
      ["APT & factor models", "Fama\u2013French, Carhart, q-factor, factor zoo"],
      ["Consumption-based models", "CCAPM, equity premium and risk-free rate puzzles"],
      ["Habit, long-run risk, rare disasters", "the main resolutions and their costs"],
      ["Intertemporal & conditional models", "ICAPM, time-varying risk premia"],
      ["Return predictability", "dividend yield, term spread, out-of-sample debate"],
    ]},
    { title: "Derivatives & contingent claims", note: "", topics: [
      ["Forwards, futures, swaps", "cost of carry, basis, mark-to-market"],
      ["Option fundamentals", "payoffs, put\u2013call parity, bounds"],
      ["Black\u2013Scholes\u2013Merton", "assumptions, derivation, replication argument"],
      ["The Greeks & hedging", "delta, gamma, vega, theta, rho, dynamic hedging"],
      ["Implied volatility", "smile, skew, term structure, volatility surface"],
      ["Local & stochastic volatility", "Dupire, Heston, SABR"],
      ["Jump and L\u00e9vy models", "Merton jump-diffusion, variance gamma"],
      ["American & exotic options", "early exercise, barriers, Asians, lookbacks"],
      ["Credit derivatives", "CDS pricing, CDO tranches, correlation"],
      ["Volatility products", "VIX, variance swaps, volatility risk premium"],
    ]},
    { title: "Fixed income & credit", note: "", topics: [
      ["Bond mathematics", "yield, duration, convexity, immunisation"],
      ["Yield curve construction", "bootstrapping, splines, discount factors"],
      ["Term structure theories", "expectations hypothesis, term premia, segmentation"],
      ["Short-rate models", "Vasicek, CIR, Hull\u2013White, calibration"],
      ["Forward-rate & affine models", "HJM, LIBOR/SOFR market models"],
      ["Structural credit models", "Merton, distance to default, KMV"],
      ["Reduced-form credit models", "hazard rates, recovery, default correlation"],
      ["Securitisation", "MBS, prepayment risk, tranching, ABS"],
      ["Sovereign & municipal debt", "default risk, restructuring, ratings"],
    ]},
    { title: "Corporate finance", note: "", topics: [
      ["Capital budgeting", "NPV, IRR pitfalls, cash-flow estimation"],
      ["Cost of capital", "WACC, beta estimation, hurdle rates"],
      ["Modigliani\u2013Miller", "with and without taxes; what the propositions really assume"],
      ["Capital structure theories", "trade-off, pecking order, market timing"],
      ["Financial distress & bankruptcy", "direct and indirect costs, Chapter 11 vs liquidation"],
      ["Payout policy", "dividends vs buybacks, signalling, clientele"],
      ["Agency theory", "manager\u2013shareholder and shareholder\u2013creditor conflicts"],
      ["Corporate governance", "boards, compensation, blockholders, activism"],
      ["Mergers & acquisitions", "synergies, method of payment, returns to acquirers"],
      ["Private equity & LBOs", "value creation, leverage, exits"],
      ["IPOs & security issuance", "underpricing, long-run performance, SEOs, SPACs"],
      ["Real options", "expansion, abandonment, timing under irreversibility"],
    ]},
    { title: "Market microstructure", note: "", topics: [
      ["Market designs", "quote-driven vs order-driven, auctions, dark pools"],
      ["Limit order books", "depth, resiliency, order types"],
      ["Spread decomposition", "order processing, inventory, adverse selection"],
      ["Kyle model", "informed trading, market depth, price informativeness"],
      ["Glosten\u2013Milgrom", "sequential trade and learning"],
      ["Price discovery", "information shares, lead\u2013lag across venues"],
      ["Liquidity measures", "Amihud, effective spread, Kyle's lambda"],
      ["High-frequency trading", "latency arbitrage, market making, flash events"],
      ["Execution & transaction costs", "implementation shortfall, optimal execution"],
    ]},
    { title: "Empirical finance", note: "", topics: [
      ["Event studies", "abnormal returns, estimation windows, inference"],
      ["Cross-sectional asset pricing tests", "Fama\u2013MacBeth, GRS, errors in variables"],
      ["GMM tests of Euler equations", "Hansen\u2013Jagannathan bounds and distance"],
      ["Portfolio sorts & factor construction", "breakpoints, weighting, robustness"],
      ["Anomalies and their fragility", "multiple testing, publication bias, decay"],
      ["Volatility estimation", "GARCH family, realised volatility, high-frequency data"],
      ["Predictive regressions", "Stambaugh bias, out-of-sample evaluation"],
      ["Machine learning in asset pricing", "return prediction, shrinkage, interpretation"],
    ]},
    { title: "Financial intermediation & institutions", note: "", topics: [
      ["Why banks exist", "delegated monitoring, maturity transformation"],
      ["Diamond\u2013Dybvig", "runs, deposit insurance, multiple equilibria"],
      ["Capital & liquidity regulation", "Basel framework, leverage ratio, LCR/NSFR"],
      ["Money markets & repo", "collateral, haircuts, run dynamics"],
      ["Shadow banking", "money market funds, securitisation chains"],
      ["Central clearing & market infrastructure", "CCPs, margin, netting"],
      ["Systemic risk", "contagion, fire sales, funding spirals, macroprudential policy"],
      ["Financial crises", "history, anatomy, lender of last resort, resolution"],
    ]},
    { title: "Behavioural finance", note: "", topics: [
      ["Limits to arbitrage", "noise trader risk, funding constraints, horizon risk"],
      ["Investor biases", "overconfidence, disposition effect, attention, extrapolation"],
      ["Prospect theory applications", "loss aversion in asset pricing"],
      ["Sentiment", "measurement, cross-sectional effects"],
      ["Bubbles", "rational bubbles, herding, riding the bubble"],
      ["Household finance", "under-diversification, participation puzzles, financial literacy"],
    ]},
    { title: "Risk management", note: "", topics: [
      ["Value at Risk & expected shortfall", "estimation, backtesting, limitations"],
      ["Coherent risk measures", "axioms, subadditivity"],
      ["Dependence modelling", "correlation, copulas, tail dependence"],
      ["Stress testing & scenario analysis", "regulatory and internal frameworks"],
      ["Counterparty risk & XVA", "CVA, DVA, FVA, collateral"],
      ["Model risk", "validation, parameter uncertainty, misspecification"],
      ["Operational and liquidity risk", "measurement and controls"],
    ]},
    { title: "International & alternative markets", note: "", topics: [
      ["FX market structure", "spot, forwards, order flow"],
      ["Carry trade & forward premium puzzle", "the central FX anomaly"],
      ["International portfolio choice", "home bias, hedging currency exposure"],
      ["Commodities", "convenience yield, storage, futures curves"],
      ["Real estate", "valuation, REITs, illiquidity"],
      ["Private markets", "venture capital, PE returns measurement, J-curve"],
      ["Digital assets", "crypto market structure, stablecoins, DeFi mechanics"],
      ["ESG & sustainable finance", "screening, greenium, measurement problems"],
    ]},
    { title: "Portfolio management practice", note: "", topics: [
      ["Strategic vs tactical allocation", "policy portfolios, rebalancing"],
      ["Estimation error", "Black\u2013Litterman, shrinkage, resampling"],
      ["Factor investing", "smart beta, crowding, capacity"],
      ["Performance evaluation", "Sharpe, information ratio, alpha attribution"],
      ["Benchmarking & tracking error", "active share, risk budgeting"],
      ["Liability-driven investing", "pensions, insurance ALM"],
      ["Taxes, costs and turnover", "after-tax and net-of-fee performance"],
    ]},
  ]
});
