/* ═══════════ LAW ═══════════
   Weighted toward Indian law, as requested. Comparative and international
   material is here to give the Indian position context, not to compete with it.
   Edit freely — see data/README inside the app for the shape. */

SUBJECTS.push({
  id: 'law',
  name: 'Law',
  short: 'Law',
  accent: 'violet',
  level: 'Indian practice depth, with comparative and international context',
  blurb: 'Indian law sits on a common-law skeleton with a written supremacy-of-constitution spine and a statutory layer that was substantially rewritten in 2023. Mastery means holding the doctrine, the leading judgments, and the procedure in the same head.',
  sections: [
    { title: 'Jurisprudence and legal theory', note: 'The questions underneath every rule.', topics: [
      ['Natural law tradition', 'law as derived from morality; Aquinas, Fuller, Finnis'],
      ['Legal positivism', 'Austin\'s command theory, Hart\'s rule of recognition, the separation thesis'],
      ['Hart–Fuller and Hart–Devlin debates', 'law vs morality; enforcement of morals'],
      ['Dworkin\'s interpretivism', 'principles vs rules, law as integrity, the right answer thesis'],
      ['Sociological and realist schools', 'Pound, Holmes, Llewellyn; law in action vs law in books'],
      ['Analytical concepts', 'Hohfeldian rights, duties, powers, immunities'],
      ['Theories of punishment', 'retribution, deterrence, reform, restorative justice'],
      ['Theories of justice', 'Rawls, Nozick, Sen\'s capability approach and its Indian reception'],
      ['Feminist and critical legal studies', 'indeterminacy, power, and the subject of law'],
      ['Ambedkar\'s constitutional thought', 'annihilation of caste, constitutional morality, social democracy'],
    ]},
    { title: 'Legal terminology and maxims', note: 'The vocabulary courts assume you already have.', topics: [
      ['Ratio decidendi and obiter dicta', 'what binds and what merely persuades'],
      ['Stare decisis in India', 'Article 141, per incuriam, sub silentio, prospective overruling'],
      ['Audi alteram partem', 'no one condemned unheard; the core of natural justice'],
      ['Nemo judex in causa sua', 'rule against bias; pecuniary, personal, official'],
      ['Res judicata and res sub judice', 'finality of decided matters; Section 11 CPC'],
      ['Ultra vires', 'acting beyond conferred power; substantive and procedural'],
      ['Mens rea and actus reus', 'the guilty mind and the guilty act; strict liability exceptions'],
      ['Locus standi and PIL relaxation', 'who may sue, and how India loosened it'],
      ['Estoppel and promissory estoppel', 'Section 115 Evidence Act; against the State'],
      ['Common Latin maxims', 'volenti non fit injuria, ubi jus ibi remedium, ignorantia juris non excusat, ejusdem generis'],
      ['Interpretation of statutes', 'literal, golden and mischief rules; purposive construction; noscitur a sociis'],
    ]},
    { title: 'Constitutional law of India — structure', note: '', topics: [
      ['Preamble', 'sovereign socialist secular democratic republic; its interpretive weight'],
      ['Union and its territory', 'Articles 1–4; reorganisation of states by simple majority'],
      ['Citizenship', 'Articles 5–11; Citizenship Act 1955 and its amendments'],
      ['Federal structure', 'quasi-federal design, Seventh Schedule lists, residuary power'],
      ['Executive', 'President, Governor, Council of Ministers; Articles 74 and 163'],
      ['Parliament and state legislatures', 'composition, privileges, money bills, anti-defection under Tenth Schedule'],
      ['Judiciary', 'Supreme Court and High Courts, collegium system, judicial independence'],
      ['Centre–state relations', 'legislative, administrative and financial; Article 356 and its limits'],
      ['Emergency provisions', 'national, state and financial emergency; the 44th Amendment safeguards'],
      ['Local government', '73rd and 74th Amendments; panchayats and municipalities'],
      ['Constitutional amendment', 'Article 368 procedure and its substantive limits'],
    ]},
    { title: 'Constitutional law of India — rights', note: 'Where most litigation actually lives.', topics: [
      ['Definition of State', 'Article 12 and the expanding test for instrumentality'],
      ['Article 13 and judicial review', 'laws inconsistent with fundamental rights; doctrines of severability and eclipse'],
      ['Right to equality', 'Articles 14–18; reasonable classification vs manifest arbitrariness'],
      ['Reservation jurisprudence', 'Articles 15(4), 16(4); Indra Sawhney, creamy layer, the 50 per cent rule, EWS'],
      ['Freedoms under Article 19', 'speech, assembly, association, movement, profession; reasonable restrictions'],
      ['Free speech doctrine', 'Shreya Singhal, sedition, hate speech, obscenity, contempt'],
      ['Article 21', 'life and personal liberty; procedure established by law read as due process'],
      ['Expanded Article 21 rights', 'privacy, dignity, livelihood, health, clean environment, speedy trial'],
      ['Protection in criminal matters', 'Articles 20 and 22; double jeopardy, self-incrimination, preventive detention'],
      ['Religious and cultural rights', 'Articles 25–30; essential religious practices doctrine, minority institutions'],
      ['Constitutional remedies', 'Article 32 and 226; the five writs and when each lies'],
      ['Directive Principles and Fundamental Duties', 'Parts IV and IVA; non-justiciable but interpretively powerful'],
    ]},
    { title: 'Landmark Indian judgments', note: 'Know the holding, the bench, and what it displaced.', topics: [
      ['Kesavananda Bharati (1973)', 'basic structure doctrine; amending power is wide but not unlimited'],
      ['Indira Nehru Gandhi v Raj Narain (1975)', 'free and fair elections as basic structure'],
      ['ADM Jabalpur (1976)', 'the emergency-era low point; overruled in Puttaswamy'],
      ['Maneka Gandhi (1978)', 'Articles 14, 19 and 21 read together; procedure must be fair and reasonable'],
      ['Minerva Mills (1980)', 'limited amending power and balance between rights and directive principles'],
      ['Olga Tellis (1985)', 'right to livelihood as part of the right to life'],
      ['Shah Bano (1985)', 'maintenance under Section 125 CrPC and the legislative reversal that followed'],
      ['MC Mehta line of cases', 'absolute liability, polluter pays, precautionary principle'],
      ['Indra Sawhney (1992)', 'OBC reservation, creamy layer, the ceiling on reservation'],
      ['SR Bommai (1994)', 'President\'s Rule is justiciable; secularism as basic structure'],
      ['Vishaka (1997)', 'judicial guidelines on workplace sexual harassment; later the POSH Act'],
      ['Puttaswamy (2017)', 'privacy as a fundamental right; the proportionality test'],
      ['Shayara Bano (2017)', 'instant triple talaq struck down'],
      ['Navtej Singh Johar (2018)', 'Section 377 read down; constitutional morality over social morality'],
      ['Recent constitutional benches', 'electoral bonds, Article 370, same-sex marriage, sub-classification of SCs'],
    ]},
    { title: 'Criminal law', note: 'The 2023 statutes replaced the colonial trio — know both names.', topics: [
      ['Bharatiya Nyaya Sanhita 2023', 'replaced the IPC; renumbering, new offences, community service'],
      ['Bharatiya Nagarik Suraksha Sanhita 2023', 'replaced the CrPC; timelines, e-FIR, zero FIR, forensic mandates'],
      ['Bharatiya Sakshya Adhiniyam 2023', 'replaced the Evidence Act; electronic records as primary evidence'],
      ['General exceptions', 'mistake, accident, necessity, consent, private defence, insanity'],
      ['Inchoate offences', 'attempt, abetment, criminal conspiracy'],
      ['Offences against the person', 'culpable homicide vs murder, grievous hurt, kidnapping'],
      ['Sexual offences', 'the 2013 amendments, consent, POCSO, marital rape exception debate'],
      ['Offences against property', 'theft, extortion, robbery, dacoity, criminal breach of trust, cheating'],
      ['Investigation and trial', 'FIR, arrest, bail, charge, examination, appeal, sentencing'],
      ['Special criminal statutes', 'NDPS, UAPA, PMLA, POCSO, SC/ST Act; reverse burdens and bail bars'],
      ['Bail jurisprudence', 'anticipatory bail, default bail, the triple test, Arnesh Kumar guidelines'],
    ]},
    { title: 'Contract, tort and commercial law', note: '', topics: [
      ['Formation of contract', 'offer, acceptance, consideration, capacity; Indian Contract Act 1872'],
      ['Free consent', 'coercion, undue influence, fraud, misrepresentation, mistake'],
      ['Void and voidable agreements', 'Sections 23–30; restraint of trade, wagering, public policy'],
      ['Discharge and breach', 'performance, frustration under Section 56, damages under Hadley v Baxendale'],
      ['Specific relief', 'Specific Relief Act 1963 as amended in 2018; injunctions'],
      ['Special contracts', 'indemnity, guarantee, bailment, pledge, agency'],
      ['Sale of goods and negotiable instruments', 'conditions and warranties, Section 138 cheque dishonour'],
      ['Tort fundamentals', 'duty, breach, causation, remoteness; no codified Indian tort statute'],
      ['Specific torts', 'negligence, nuisance, defamation, trespass, vicarious liability'],
      ['Strict and absolute liability', 'Rylands v Fletcher and the Indian departure in Oleum Gas'],
      ['Consumer protection', 'Consumer Protection Act 2019; product liability, e-commerce rules'],
    ]},
    { title: 'Corporate, tax and regulatory law', note: '', topics: [
      ['Companies Act 2013', 'incorporation, separate legal personality, lifting the veil'],
      ['Directors and governance', 'duties under Section 166, independent directors, board committees'],
      ['Shares and capital', 'issue, transfer, buyback, reduction, related party transactions'],
      ['Insolvency and Bankruptcy Code 2016', 'CIRP, moratorium, resolution plan, waterfall under Section 53'],
      ['Securities regulation', 'SEBI Act, LODR, insider trading, takeover code'],
      ['Competition law', 'Competition Act 2002; anti-competitive agreements, abuse of dominance, combinations'],
      ['Direct tax', 'Income Tax Act, residence, heads of income, capital gains, GAAR'],
      ['Indirect tax', 'GST structure, supply, input tax credit, place of supply, GST Council'],
      ['Banking and financial regulation', 'RBI powers, NPA framework, FEMA, PMLA compliance'],
      ['Data and technology law', 'IT Act 2000, Digital Personal Data Protection Act 2023, intermediary liability'],
    ]},
    { title: 'Personal, property and labour law', note: '', topics: [
      ['Hindu personal law', 'marriage, succession under the 1956 Act and the 2005 amendment, adoption, maintenance'],
      ['Muslim personal law', 'nikah, mahr, talaq, iddat, waqf, inheritance shares'],
      ['Christian and Parsi personal law', 'and the Special Marriage Act 1954 as a secular option'],
      ['Uniform Civil Code debate', 'Article 44, Shah Bano and Sarla Mudgal, the Uttarakhand statute'],
      ['Family courts and child law', 'custody, guardianship, welfare principle, Juvenile Justice Act'],
      ['Transfer of Property Act 1882', 'sale, mortgage, lease, gift, exchange; doctrine of part performance'],
      ['Land and tenancy', 'land acquisition under the 2013 Act, ceiling laws, RERA'],
      ['Labour codes', 'the four consolidated codes on wages, industrial relations, social security, OSH'],
      ['Industrial disputes', 'strikes, lockouts, layoff, retrenchment, unfair labour practices'],
      ['Intellectual property', 'Patents Act and Section 3(d), copyright, trademarks, designs, GI'],
    ]},
    { title: 'Procedure, evidence and dispute resolution', note: '', topics: [
      ['Civil Procedure Code 1908', 'jurisdiction, pleadings, issues, decree, execution, appeal, review'],
      ['Limitation Act 1963', 'periods, condonation of delay, acknowledgment'],
      ['Law of evidence', 'relevance, admissibility, burden of proof, presumptions'],
      ['Documentary and electronic evidence', 'primary vs secondary, Section 65B certification and its case law'],
      ['Witnesses and examination', 'examination in chief, cross-examination, hostile witness'],
      ['Confessions and dying declarations', 'to police vs magistrate; evidentiary weight'],
      ['Writ and appellate practice', 'Article 226 vs 32, SLP under Article 136, curative petition'],
      ['Arbitration', 'Arbitration and Conciliation Act 1996 as amended; seat vs venue, Section 34 challenge'],
      ['Mediation and Lok Adalat', 'Mediation Act 2023, Legal Services Authorities Act'],
      ['Legal ethics and professional conduct', 'Advocates Act 1961, Bar Council rules, contempt'],
    ]},
    { title: 'International law', note: '', topics: [
      ['Sources of international law', 'Article 38 ICJ Statute; treaties, custom, general principles, jus cogens'],
      ['Treaty law', 'Vienna Convention 1969; reservations, interpretation, termination'],
      ['International law in Indian courts', 'dualist position, Article 51 and 253, Vishaka\'s use of CEDAW'],
      ['Statehood and recognition', 'Montevideo criteria, self-determination, succession'],
      ['Jurisdiction and immunity', 'territorial, nationality, universal; sovereign and diplomatic immunity'],
      ['United Nations system', 'Charter, Security Council, General Assembly, use of force under Article 2(4) and 51'],
      ['International humanitarian law', 'Geneva Conventions, distinction, proportionality, war crimes'],
      ['International human rights', 'UDHR, ICCPR, ICESCR, treaty bodies, India\'s reservations'],
      ['International courts', 'ICJ, ICC and India\'s non-membership, ITLOS, arbitral tribunals'],
      ['Law of the sea and airspace', 'UNCLOS zones, EEZ, continental shelf; the Enrica Lexie dispute'],
      ['International economic law', 'WTO agreements, dispute settlement, BITs and investor-state arbitration'],
      ['International environmental law', 'UNFCCC, Paris Agreement, CBDR, transboundary harm'],
    ]},
  ]
});
