/* ═══════════ POLITICS ═══════════ */

SUBJECTS.push({
  id: 'politics',
  name: 'Politics',
  short: 'Politics',
  accent: 'magenta',
  level: 'Undergraduate to graduate depth, India-weighted',
  blurb: 'Politics is the study of who decides, by what authority, and what constrains them. The theory travels; the institutions do not, so the comparative sections matter as much as the conceptual ones.',
  sections: [
    { title: 'Political theory', note: '', topics: [
      ['Classical political thought', 'Plato, Aristotle, Kautilya\'s Arthashastra, Cicero'],
      ['Social contract tradition', 'Hobbes, Locke, Rousseau; state of nature and consent'],
      ['Liberalism', 'classical and modern; Mill, Rawls, negative and positive liberty'],
      ['Conservatism', 'Burke, tradition, organic change, institutional scepticism'],
      ['Socialism and Marxism', 'historical materialism, class, alienation, revisionism'],
      ['Anarchism and libertarianism', 'Nozick\'s entitlement theory, minimal state, mutualism'],
      ['Feminist political theory', 'public-private divide, intersectionality, care ethics'],
      ['Postcolonial thought', 'Fanon, Said, subaltern studies, decolonising the state'],
      ['Indian political thought', 'Gandhi, Ambedkar, Nehru, Tagore, Savarkar, Lohia, JP Narayan'],
      ['Concepts of power and legitimacy', 'Weber\'s three types, Lukes\' three faces, hegemony'],
      ['Democracy and its theories', 'representative, deliberative, participatory; Schumpeter vs Dahl'],
    ]},
    { title: 'Comparative politics', note: '', topics: [
      ['Comparative method', 'most similar and most different designs, selection bias, N problems'],
      ['Regime types', 'democracy, hybrid regimes, competitive authoritarianism, totalitarianism'],
      ['Executive systems', 'presidential, parliamentary, semi-presidential; the perils of presidentialism debate'],
      ['Electoral systems', 'first past the post, proportional representation, mixed member, ranked choice'],
      ['Duverger\'s law', 'how electoral rules shape party systems'],
      ['Party systems', 'dominant, two-party, multiparty; cleavage theory'],
      ['Federalism and decentralisation', 'coming-together vs holding-together federations'],
      ['State capacity', 'extraction, coercion, administration; why some states deliver'],
      ['Democratic backsliding', 'executive aggrandisement, institutional capture, measurement debates'],
      ['Revolutions and social movements', 'resource mobilisation, political opportunity structure'],
    ]},
    { title: 'Indian government and politics', note: 'The core section.', topics: [
      ['Constitutional design', 'Constituent Assembly debates, borrowed features, the federal bargain'],
      ['Parliament', 'Lok Sabha and Rajya Sabha, committees, question hour, declining sitting days'],
      ['Executive', 'PMO centralisation, Cabinet Secretariat, Council of Ministers'],
      ['Judiciary in politics', 'judicial review, PIL, collegium vs NJAC, judicial appointments'],
      ['Federalism in practice', 'Governor\'s role, Article 356, GST Council, fiscal transfers'],
      ['Party system evolution', 'Congress dominance, the 1989 rupture, coalition era, BJP dominance'],
      ['Elections and the ECI', 'model code of conduct, EVMs, delimitation, electoral bonds and funding'],
      ['Caste and politics', 'Mandal, OBC mobilisation, Dalit politics, dominant caste theory'],
      ['Religion and secularism', 'Indian secularism as principled distance, communal mobilisation'],
      ['Regional and state politics', 'Dravidian parties, Left in Kerala and Bengal, Northeast, Kashmir'],
      ['Bureaucracy and public administration', 'IAS structure, lateral entry, administrative reform'],
      ['Civil society and media', 'RTI, NGOs, press freedom, social media and political communication'],
      ['Policy landmarks', 'liberalisation 1991, MGNREGA, Aadhaar, GST, farm laws and their repeal'],
    ]},
    { title: 'United States politics', note: '', topics: [
      ['Constitutional framework', 'separation of powers, checks and balances, federalism, Bill of Rights'],
      ['Congress', 'bicameralism, committees, filibuster, reconciliation, gridlock'],
      ['Presidency', 'executive orders, veto, war powers, the administrative state'],
      ['Supreme Court', 'judicial review since Marbury, originalism vs living constitutionalism, confirmation politics'],
      ['Elections', 'primaries, Electoral College, midterms, gerrymandering, campaign finance after Citizens United'],
      ['Party system', 'realignments, polarisation, the coalition composition of both parties'],
      ['Interest groups and lobbying', 'pluralism vs elite capture, PACs'],
      ['Federal-state tensions', 'preemption, state-level policy divergence, sanctuary jurisdictions'],
      ['Race and American politics', 'civil rights movement, Voting Rights Act, contemporary debates'],
      ['US foreign policy making', 'NSC, Congress vs executive, domestic sources of foreign policy'],
    ]},
    { title: 'United Kingdom and Europe', note: '', topics: [
      ['Uncodified constitution', 'conventions, parliamentary sovereignty, rule of law'],
      ['Westminster system', 'fusion of powers, cabinet government, collective responsibility'],
      ['UK Parliament', 'Commons, Lords reform, whips, private members bills'],
      ['Devolution', 'Scotland, Wales, Northern Ireland; the Good Friday settlement'],
      ['UK party politics', 'Labour, Conservative, Liberal Democrats, SNP, Reform; class dealignment'],
      ['Brexit', 'referendum politics, withdrawal, Northern Ireland protocol, aftermath'],
      ['European Union institutions', 'Commission, Council, Parliament, Court of Justice'],
      ['EU integration theory', 'neofunctionalism, intergovernmentalism, democratic deficit'],
      ['European party politics', 'coalition governance, rise of populist parties, Franco-German axis'],
      ['European security', 'NATO, strategic autonomy, response to the Ukraine war'],
    ]},
    { title: 'China, Russia and other major powers', note: '', topics: [
      ['Chinese political system', 'CCP structure, Politburo Standing Committee, party-state fusion'],
      ['Chinese governance', 'cadre evaluation, provincial competition, social management'],
      ['Chinese foreign policy', 'Belt and Road, South China Sea, wolf warrior diplomacy, Taiwan'],
      ['Russian political system', 'super-presidentialism, siloviki, managed elections'],
      ['Russian foreign policy', 'near abroad doctrine, energy leverage, Ukraine war and its consequences'],
      ['Japan and South Korea', 'LDP dominance, constitutional pacifism, alliance politics'],
      ['Middle East politics', 'Gulf monarchies, Iran\'s system, Israel-Palestine, regional realignment'],
      ['African politics', 'post-colonial state formation, resource politics, democratisation waves'],
      ['Latin American politics', 'presidentialism, populism, the pink tide and its reversals'],
      ['South Asian neighbourhood', 'Pakistan\'s civil-military balance, Bangladesh, Sri Lanka, Nepal'],
    ]},
    { title: 'International relations', note: '', topics: [
      ['Realism', 'classical and neorealism, anarchy, balance of power, security dilemma'],
      ['Liberalism in IR', 'institutions, interdependence, democratic peace theory'],
      ['Constructivism', 'norms, identity, anarchy is what states make of it'],
      ['Critical approaches', 'Marxist, postcolonial and feminist IR'],
      ['Foreign policy analysis', 'levels of analysis, bureaucratic politics, two-level games'],
      ['International organisations', 'UN system, Security Council reform, WTO, IMF, World Bank'],
      ['Regional organisations', 'ASEAN, EU, African Union, SAARC and BIMSTEC, QUAD, BRICS'],
      ['Diplomacy and statecraft', 'negotiation, signalling, sanctions, coercive diplomacy'],
      ['India\'s foreign policy', 'non-alignment to multi-alignment, China border, US ties, Russia balance, neighbourhood first'],
      ['Nuclear politics', 'deterrence theory, NPT, India\'s doctrine and no-first-use debate'],
    ]},
    { title: 'Security, conflict and geopolitics', note: '', topics: [
      ['Causes of war', 'bargaining model, commitment problems, diversionary war'],
      ['Civil war and insurgency', 'greed vs grievance, counterinsurgency doctrine'],
      ['Terrorism', 'definitions, radicalisation, counterterrorism trade-offs with civil liberties'],
      ['Nuclear strategy', 'mutually assured destruction, second strike, escalation ladders'],
      ['Cyber and hybrid conflict', 'attribution problem, information operations, critical infrastructure'],
      ['Grand strategy', 'offshore balancing, primacy, restraint; how states choose'],
      ['Geoeconomics', 'sanctions, export controls, supply chain weaponisation, chip politics'],
      ['Maritime geopolitics', 'chokepoints, Indian Ocean strategy, freedom of navigation'],
      ['Space and emerging domains', 'militarisation, ASAT tests, satellite dependence'],
      ['Human security and intervention', 'responsibility to protect, humanitarian intervention debates'],
    ]},
    { title: 'Political economy and public policy', note: '', topics: [
      ['State and market', 'developmental state, neoliberalism, industrial policy revival'],
      ['Comparative capitalism', 'liberal vs coordinated market economies'],
      ['Welfare states', 'Esping-Andersen typology, universal vs targeted provision'],
      ['Inequality and redistribution', 'Meltzer-Richard model, why democracies underredistribute'],
      ['Public choice theory', 'rent-seeking, regulatory capture, bureaucratic incentives'],
      ['Policy process models', 'stages heuristic, multiple streams, advocacy coalitions, punctuated equilibrium'],
      ['Policy evaluation', 'cost-benefit analysis, RCTs in policy, implementation gap'],
      ['Indian political economy', 'licence raj, 1991 reforms, informality, welfare delivery and DBT'],
      ['Climate politics', 'international negotiation, CBDR, domestic coalitions, just transition'],
      ['Technology and governance', 'platform regulation, digital public infrastructure, AI policy'],
    ]},
    { title: 'Political behaviour and methods', note: '', topics: [
      ['Voting behaviour', 'sociological, psychological and rational choice models'],
      ['Public opinion', 'formation, measurement, polling error, framing effects'],
      ['Political communication', 'agenda setting, priming, media effects, misinformation'],
      ['Political participation', 'turnout puzzles, protest, clientelism and vote buying'],
      ['Identity politics', 'ethnicity, religion, language as political cleavages'],
      ['Populism', 'definitional debates, supply and demand side explanations'],
      ['Survey research methods', 'sampling, question design, social desirability bias'],
      ['Quantitative methods in political science', 'regression, causal identification, panel data'],
      ['Qualitative methods', 'case studies, process tracing, interviews, ethnography'],
      ['Formal theory', 'spatial models, median voter theorem, coalition formation'],
    ]},
  ]
});
